<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/
	
	// Bing Keys - DJDJ2000 key
	'bing_market' => 'en-us',
	'bing_key' => 'G70wwZhMZQZEIJ7HEMwzxQoNCs+YuYb76cZxL6q73kg',
	// Filter for Image downloads - Size(Small,Medium,Large) - Aspect(Square,Wide,Tall) - Color(Color,Monochrome) - Style(Photo,Graphic) - Face(Face,Portrait,Other)
	//Add +Aspect:Wide
	'bing_filters' => 'Size:Large+Style:Graphic+Color:Monochrome',

	//Image sizes dimensions
	'image_quality' => '85',
	'width_min' => '400',
	'height_min' => '300',
	'prefix_sm' => '',
	'suffix_sm' => '-sm',
	'prefix_md' => '',
	'suffix_md' => '-md',
	'prefix_bg' => '',
	'suffix_bg' => '',
	'width_sm_max' => '300',
	'height_sm_max' => '200',
	'autocrop_sm' => '0',
	'width_md_max' => '610',
	'height_md_max' => '700',
	'width_bg_max' => '1920',
	'height_bg_max' => '1080',
	'image_folder_path' => '/var/www/crazycoloringpages.com/images/',
	'image_folder_path_web' => '/images/',
	
	//Tag config
	'tag1_isactive' => 1,
	'tag2_isactive' => 0,
	'tag3_isactive' => 0,
	'tag1_label' => 'Types',
	'tag2_label' => 'Types',
	'tag3_label' => 'Types',
	
	//Wallpaper - Multi Image Size config
	'enable_wallpaper' => 0,
	'enable_wallpaper_sizes' => array('1366x768','1280x800','1600x900','1440x900','1360x768','1920x1080'),
	
	
	//Other
	'base_url' => 'http://www.crazycoloringpages.com',
	//What is the folder of the theme
	'theme_folder' => 'gvar1',
	//Don't download images from these websites
	'domain_ban' => array('www.youtube.com','www.flickr.com','coloringbookarea.com','yoall.us','99coloring.com','en.wikipedia.org','commons.wikimedia.org','shutterstock.com','www.visualphotos.com','fotolia.com','dreamstime.com','gettyimages.com','123rf.com','istockphoto.com','coloringset.net'),
	'pre_process_stage' => 'new_keyword',
	'in_process_stage' => 'in_process',
	'post_process_stage' => 'published',
	'max_images_per_keyword' => '49',
	'pagination' => '8',
	'number_of_related' => '5',
	'enable_ads' => '1',
	//'google_analytics_id' => '53201784-1',
	'google_analytics_id' => '62038604-1',
	'sitemap_folder' => 'sitemap',
	//How many posts will get processed automatically when crontab runs
	'automatic_posts' => '1',
	
	// NOTE - In the Front Controller all the 'META' tags have to be updated accordingly
	'meta_title_postfix' => ' | Crazy Coloring Pages',
);